name: Maven Package

on:
  push:
    branches:
      - master
      - shervann
      - 'release/**'
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github</id><username>danieldieeins</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ${{ github.workspace }}/settings.xml

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Build with Maven
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean package --settings ${{ github.workspace }}/settings.xml
          mv /home/runner/work/Zyneon-Application/Zyneon-Application/application-main/target/application-main-${{ steps.extract_version.outputs.version }}.jar /home/runner/work/Zyneon-Application/Zyneon-Application/application-main/target/application-main-experimental.jar

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: application-experimental
          path: /home/runner/work/Zyneon-Application/Zyneon-Application/application-main/target/application-main-experimental.jar

      - name: Create Tag
        if: success() && github.event_name == 'push' && github.ref_type == 'tag'
        run: git tag -a v${{ steps.extract_version.outputs.version }} -m "Release version v${{ steps.extract_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        if: success() && github.event_name == 'push' && github.ref_type == 'tag'
        run: git push origin v${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: /home/runner/work/Zyneon-Application/Zyneon-Application/application-main/target/application-main-experimental.jar
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            Release ${{ steps.extract_version.outputs.version }}
