name: Maven Package

on:
  push:
    branches:
      - master
      - shervann
      - 'release/**'
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github</id><username>danieldieeins</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ${{ github.workspace }}/settings.xml

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Build with Maven
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean package --settings ${{ github.workspace }}/settings.xml